from .filemap import load_filemap, recover_filemap, write_filemap_atomic
from .initializer import initialize_vault
from .ledger import append_tombstone, load_tombstone_ledger
from .models import FileMapDocument, FileRecord, TombstoneRecord, VaultStateRecord, WikiTaskRecord
from .models import CommitIntentJournalRecord, SyncApplyJournalRecord
from .operations import add_file, mark_deleted, register_conflict_copy, rename_file
from .paths import allocate_conflict_copy_path, move_conflict_orphan, move_staging_orphan, sanitize_device_name
from .recovery import (
    apply_prepared_commit_recovery,
    apply_submitted_commit_match_recovery,
    apply_submitted_commit_miss_recovery,
    apply_sync_finalizing_recovery,
    normalize_commit_journal_for_recovery,
    select_pending_tombstones_for_commit,
    should_block_new_commit,
)
from .sqlite_store import (
    bootstrap_database,
    clear_commit_intent_journal,
    clear_sync_apply_journal,
    list_file_index,
    load_commit_intent_journal,
    load_sync_apply_journal,
    load_vault_state,
    normalize_legacy_acknowledged_commit_intent,
    open_database,
    recover_prepared_commit_cleanup,
    recover_submitted_commit_match,
    recover_submitted_commit_miss,
    recover_sync_apply_finalizing_state,
    replace_active_wiki_task,
    upsert_commit_intent_journal,
    upsert_file_index_entry,
    upsert_sync_apply_journal,
    upsert_vault_state,
)

__all__ = [
    "FileMapDocument",
    "FileRecord",
    "TombstoneRecord",
    "CommitIntentJournalRecord",
    "SyncApplyJournalRecord",
    "VaultStateRecord",
    "WikiTaskRecord",
    "add_file",
    "allocate_conflict_copy_path",
    "apply_prepared_commit_recovery",
    "apply_submitted_commit_match_recovery",
    "apply_submitted_commit_miss_recovery",
    "apply_sync_finalizing_recovery",
    "append_tombstone",
    "bootstrap_database",
    "clear_commit_intent_journal",
    "clear_sync_apply_journal",
    "initialize_vault",
    "list_file_index",
    "load_commit_intent_journal",
    "load_sync_apply_journal",
    "load_tombstone_ledger",
    "load_filemap",
    "load_vault_state",
    "mark_deleted",
    "move_conflict_orphan",
    "move_staging_orphan",
    "normalize_legacy_acknowledged_commit_intent",
    "normalize_commit_journal_for_recovery",
    "open_database",
    "recover_prepared_commit_cleanup",
    "recover_filemap",
    "recover_submitted_commit_match",
    "recover_submitted_commit_miss",
    "recover_sync_apply_finalizing_state",
    "replace_active_wiki_task",
    "register_conflict_copy",
    "rename_file",
    "sanitize_device_name",
    "select_pending_tombstones_for_commit",
    "should_block_new_commit",
    "upsert_commit_intent_journal",
    "upsert_file_index_entry",
    "upsert_sync_apply_journal",
    "upsert_vault_state",
    "write_filemap_atomic",
]
